(define 
(problem MALogistics-5-12-12-a3)
(:domain MALogistics-5-12-12-a3)
(:init
	(city-in-area C4 A3)
	(city-in-area C5 A3)
	(city-in-area C6 A3)
	(truck-in-area T3 A3)
	(truck-in-city T3 C4)
	(adj C5 C4)
	(adj C4 C5)
	(adj C6 C5)
	(adj C5 C6)
	(package-in-city P0 C6)
	(package-in-city P1 C5)
	(package-in-city P2 C5)
	(package-in-city P6 C5)
	(package-in-city P8 C4)
)
(:goal (and
	(package-in-city P0 C6)
	(package-in-city P3 C5)
	(package-in-city P4 C5)
	(package-in-city P6 C6)
	(package-in-city P8 C4)
	(package-in-city P9 C4)
	(package-in-city P10 C4)
))
)
