(define 
(problem MALogistics-5-12-12-a2)
(:domain MALogistics-5-12-12-a2)
(:init
	(city-in-area C2 A2)
	(city-in-area C0 A2)
	(truck-in-area T2 A2)
	(truck-in-city T2 C2)
	(adj C0 C2)
	(adj C2 C0)
	(package-in-city P3 C2)
	(package-in-city P4 C2)
	(package-in-city P5 C0)
	(package-in-city P8 C2)
	(package-in-city P11 C2)
)
(:goal (and
	(package-in-city P1 C2)
	(package-in-city P6 C0)
))
)
